apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Release.Name }}.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: {{ .Values.containerPort }}