version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    image: ${DOCKERHUB_DOCKER_IMAGE_NAME}
    ports:
    - 5002:1234
    environment:
      - PORT=1234
