name: Build

on:
  push:
    branches:
      - master

env:
  GITHUB_DOCKER_IMAGE_NAME: ipwa-demo
  DOCKERHUB_DOCKER_IMAGE_NAME: revathyng/ipwa-demo
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  FIREBASE_APP_NAME: ${{ secrets.FIREBASE_APP_NAME }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  CYPRESS_TOKEN: ${{ secrets.CYPRESS_TOKEN }}
  CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_REPO: ${{ github.repository }}
  GITHUB_USER: ${{ github.actor }}

jobs:
  sanity_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Sanity Checks
        run: sh ./scripts/sanity_check.sh

  release_heroku:
    runs-on: ubuntu-latest
    needs: [sanity_check]
    steps:
      - uses: actions/checkout@v2
      - name: Heroku Staging
        run: sh ./scripts/release_heroku.sh

  regression_tests:
    needs: [sanity_check, release_heroku]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Regression Tests
        run: |
          npm i
          sh ./scripts/regression_tests.sh

  release_docker_images:
    needs: [sanity_check, release_heroku, regression_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to Dockerhub
        run: sh ./scripts/release_dockerhub.sh
      - name: Push to Github Container Registry
        run: sh ./scripts/release_github.sh

  release_firebase:
    needs: [sanity_check, release_heroku, regression_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cloud functions
        run: |
          npm i
          sh ./scripts/release_firebase.sh

  release_npm:
    needs: [sanity_check, release_heroku, regression_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish package to npm
        run: sh ./scripts/release_npm.sh

  release_expo:
    needs: [sanity_check, release_heroku, regression_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to expo
        run: |
          npm i
          sh ./scripts/release_expo.sh
